# Generated by Django 5.1.6 on 2025-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[("TECH", "Tech Book"), ("NOVEL", "Novel")],
                        max_length=5,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READING", "Reading"),
                            ("DONE", "Done"),
                            ("NOT_STARTED", "Not Started"),
                        ],
                        default="NOT_STARTED",
                        max_length=11,
                    ),
                ),
            ],
        ),
    ]
